Document: appstore
Title: Debian appstore Manual
Author: <insert document author here>
Abstract: This manual describes what appstore is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/appstore/appstore.sgml.gz

Format: postscript
Files: /usr/share/doc/appstore/appstore.ps.gz

Format: text
Files: /usr/share/doc/appstore/appstore.text.gz

Format: HTML
Index: /usr/share/doc/appstore/html/index.html
Files: /usr/share/doc/appstore/html/*.html
